### ISSUE TITLE
'Button' object has no attribute 'keypad'

### ISSUE THREAD

**Issue by koreth** [thecynic/pylutron#24]
Using Home Assistant 0.87.1 which uses pylutron 0.2.0, I see this in my logs. After this message, Home Assistant stops being able to interact with my Lutron repeater.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/pylutron/__init__.py", line 149, in run
    self._recv_cb(line.decode('ascii').rstrip())
  File "/usr/local/lib/python3.6/site-packages/pylutron/__init__.py", line 382, in _recv
    handled = obj.handle_update(args)
  File "/usr/local/lib/python3.6/site-packages/pylutron/__init__.py", line 840, in handle_update
    return self._components[component].handle_update(action, params)
  File "/usr/local/lib/python3.6/site-packages/pylutron/__init__.py", line 701, in handle_update
    action, self.number, self.keypad.name))
AttributeError: 'Button' object has no attribute 'keypad'
```

**Comment by thecynic** [comment]
Please check if this could be closed

**Comment by sgrimm-sg** [comment]
The change in the PR seemed to fix it on my local system but as far as I know, the PR has yet to be included in an official Home Assistant release. Not sure what criteria you use to close issues, so maybe "it worked locally" is good enough, but if not I'll be happy to report back on it once an HA release includes the latest pylutron that has this fix.

**Comment by koreth** [comment]
This seems to be fixed in the release.
