### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by grantalewis** [thecynic/pylutron#29]
Apologies if this is repetitive information. I've made a couple of other posts elsewhere but am not sure that those have been seen.

RPi3, Hass.io. I'm encountering problems with pylutron since 0.85.1; last working version was 0.84.6.

This version of the error message was from 0.85.1:

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 287, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/light/lutron.py", line 73, in turn_off
    self._lutron_device.level = 0
  File "/usr/local/lib/python3.6/site-packages/pylutron/__init__.py", line 591, in level
    Output._ACTION_ZONE_LEVEL, "%.2f" % new_level)
  File "/usr/local/lib/python3.6/site-packages/pylutron/__init__.py", line 392, in send
    self._conn.send(op + out_cmd)
  File "/usr/local/lib/python3.6/site-packages/pylutron/__init__.py", line 91, in send
    self._send_locked(cmd)
  File "/usr/local/lib/python3.6/site-packages/pylutron/__init__.py", line 81, in _send_locked
    self._telnet.write(cmd.encode('ascii') + b'\r\n')
  File "/usr/local/lib/python3.6/telnetlib.py", line 290, in write
    self.sock.sendall(buffer)
TimeoutError: [Errno 110] Operation timed out
```

This version of the error message was from 0.87.1:

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 289, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/light/lutron.py", line 73, in turn_off
    self._lutron_device.level = 0
  File "/usr/local/lib/python3.6/site-packages/pylutron/__init__.py", line 591, in level
    Output._ACTION_ZONE_LEVEL, "%.2f" % new_level)
  File "/usr/local/lib/python3.6/site-packages/pylutron/__init__.py", line 392, in send
    self._conn.send(op + out_cmd)
  File "/usr/local/lib/python3.6/site-packages/pylutron/__init__.py", line 91, in send
    self._send_locked(cmd)
  File "/usr/local/lib/python3.6/site-packages/pylutron/__init__.py", line 81, in _send_locked
    self._telnet.write(cmd.encode('ascii') + b'\r\n')
AttributeError: 'NoneType' object has no attribute 'write'
```

I have not tried later versions than 0.87.1 but would be happy to do so and provide additional feedback.

**Comment by cdheiser** [comment]
As has been mentioned in home assistant, there is a known bug: https://github.com/thecynic/pylutron/issues/17

There's an outstanding pull request to resolve it.

**Comment by grantalewis** [comment]
Thank you, cdheiser. I appreciate the reassurance.

**Comment by grantalewis** [comment]
Tried upgrading to 0.89.1. Added your patch in custom_components, @ cdheiser. 
`.
├── ...
├── config
│   ├── custom_components
│   ├── pylutron
│    │   ├── __init__.py
`

Although I'm not seeing the same errors in the log, behavior is the same for me: Lutron entities are responsive to HA commands for a few hours but eventually lose connectivity.

Log:
`
2019-03-08 23:08:36 WARNING (MainThread) [homeassistant.setup] Setup of lutron is taking over 10 seconds.
2019-03-09 00:25:18 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error on transport TCPTransport (error status in uv_stream_t.read callback)
TimeoutError: [Errno 110] Operation timed out
2019-03-09 00:54:59 ERROR (MainThread) [homeassistant.core] Error doing job: SSL error errno:1 reason: KRB5_S_INIT
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 189, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2605)
2019-03-09 07:00:46 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1880087088] Client exceeded max pending messages [2]: 512
2019-03-09 07:22:36 WARNING (MainThread) [haffmpeg.tools] Timeout reading image.
`

**Comment by cdheiser** [comment]
I don't believe any of those errors have anything to do with pylutron or
the lutron home assistant component.  It does look like you seem to have
other connectivity issues for some reason.

**Comment by grantalewis** [comment]
Fair enough -- I admit that I don't really know what I'm looking at. I can tell you that adding the custom_component was not a solution thanks to you the the Custom Components file structure change.

**Comment by cdheiser** [comment]
If I have time soon, I could try to create an instrumented version of
pylutron for you to patch in and see what it produces.

**Comment by grantalewis** [comment]
I’d be grateful.

**Comment by cdheiser** [comment]
Can we start with changing the logging level in Home Assistant??  And when
it triggers again, grep out all pylutron entries from the homeassistant log?

logger:
  logs:
    pylutron: debug

**Comment by grantalewis** [comment]
OK, I've upgraded to 0.89.2 and added to configuration.yaml:

```
logger:
  logs:
    pylutron: debug
```

When I first enabled logging last night the Pi would reboot every ~20 minutes, so I rem'd out several configuration.yaml components. I'm surprised at how quickly the home-assistant.log fills up: 20+MB in ~45 minutes.

Strange: I'm not seeing the same errors in pylutron that I was seeing previously. But the symptoms are similar. First this morning, the HA UI in my browser doesn't reflect lights' current states. If I turn on a fan or a light, the UI doesn't update to show the change. Second, if I turn on a light in the HA UI, the light does indeed turn on and stays on, but the HA UI button toggles back to the OFF position. I saw that behavior between 9:00-9:15 AM, but there are no pylutron errors in the log for that time period -- at least not the same error I was seeing previously. (I feel a little like I'm being gaslighted.)

One entity in particular where I saw this behavior is named Amber Lamp. I grabbed 15 minutes in the log when the problem occurred. Log text is saved in the accompanying log.txt file. I removed many lines that didn't seem relevant.

[log.txt](https://github.com/thecynic/pylutron/files/2973958/log.txt)

The only entry I see in the dev panel during that time that seems to be of consequence:

```
Log Details (ERROR)
Sat Mar 16 2019 09:00:26 GMT-0400 (Eastern Daylight Time)
Error doing job: SSL error errno:1 reason: KRB5_S_INIT
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 189, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2605)
```

**Comment by cdheiser** [comment]
Can you try it again but use this config:

logger:
  default: info
  logs:
    pylutron: debug

The current log only has a few pylutron entries, and for some reason
omitting the default has set all logs to DEBUG level with definitely isn't
helping.

**Comment by grantalewis** [comment]
OK, made the logging changes you suggested. 

The problem just occurred again; unfortunately still nothing about pylutron showing in the logs. I'm beginning to wonder if the problem I'm seeing is due to something else.

Same symptom as before: I turned on a toggle in the HA UI. The light turns on, but the toggle returns to its OFF position while the light stays on.

Here's the log:

```
2019-03-17 17:09:27 WARNING (MainThread) [homeassistant.components.http] legacy_api_password support has been enabled. If you don't require it, remove the 'api_password' from your http config.
2019-03-17 17:09:32 WARNING (Recorder) [homeassistant.components.recorder.migration] Database is about to upgrade. Schema version: None
2019-03-17 17:09:46 WARNING (MainThread) [homeassistant.setup] Setup of lutron is taking over 10 seconds.
2019-03-17 17:17:24 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1841192208] Client exceeded max pending messages [2]: 512
2019-03-17 17:17:24 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1841192208] Client exceeded max pending messages [2]: 512
2019-03-17 17:27:51 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error on transport TCPTransport (error status in uv_stream_t.read callback)
TimeoutError: [Errno 110] Operation timed out2019-03-17 19:54:26 ERROR (MainThread) [homeassistant.core] Error doing job: SSL error errno:1 reason: KRB5_S_INIT
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 189, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2605)
2019-03-17 19:55:30 ERROR (MainThread) [homeassistant.core] Error doing job: SSL error errno:1 reason: KRB5_S_INIT
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 189, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2605)
2019-03-17 19:56:33 ERROR (MainThread) [homeassistant.core] Error doing job: SSL error errno:1 reason: KRB5_S_INIT
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 189, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2605)
2019-03-17 20:27:03 ERROR (MainThread) [aioharmony.hubconnector] 192.168.1.21: Connection timed out for hub 10172378
```

**Comment by cdheiser** [comment]
You could try using the 0.1.0 version of pylutron to confirm.

**Comment by grantalewis** [comment]
I believe I see your 1.0 release, Oct 11, 2016, here: https://github.com/thecynic/pylutron/releases

But wouldn't implementing that involve involve custom_components? And doesn't the new custom components file structure make that significantly different than previously?

**Comment by grantalewis** [comment]
Checking in, re-read your comment and realize now you said 0.1.0, not 1.0. Apologies.

But two problems with that: 1) I'm not sure where to find 0.1.0 and 2) even if I did, I wouldn't have a clue how to implement it given the new requirements for custom components.

I know this is a hassle but I'd really appreciate your continued assistance.

**Comment by cdheiser** [comment]
I believe you need to copy the entire lutron component into custom
components, and then you can change __init__.py like so:

REQUIREMENTS = ['pylutron==0.1.0']
I believe if/when you restart, it should pull down 0.1.0 (but it might
clash/conflict with the 0.2.0 version).  I've never tried it.

**Comment by grantalewis** [comment]
Yesterday and today I moved to a brand-new configuration. My old setup was Hass.io running on a RPi3; the new setup is a Mac running VirtualBox, 64-bit Ubuntu, Hass.io. The virtual environment will let me experiment more easily and revert to a working system when I encounter problems.

I was really hoping the new config would magically fix things, but no luck. In fact, I it's kind of remarkable that I'm experiencing the identical problem I had before. Lutron entities perform fine in 0.84.6, but later versions, including the just-released 0.90.0, exhibit exactly the same faulty behavior I described above. 

Following your instructions:

```
.
├── ...
├── config
│   ├── custom_components
│   │   ├── pylutron  
│   │   │   ├── init__.py
```

I've altered the contents of **__init__.py** to this only:
`
REQUIREMENTS = ['pylutron==0.1.0']
`

I just made the change and rebooted a few minutes ago. I'll need to keep testing over the next several hours to see if this results in a favorable change. I'll report back.

**Comment by grantalewis** [comment]
Problem is still the same: toggle a Lutron light, the light goes on and stays on while the HA toggle returns to its off position. At that point the toggle loses the ability to further control the entity.

This doesn't happen with toggles controlling other entities, only Lutron.

Is there a way to tell if HA is actually using the pylutron==0.1.0 custom_component? I have a hunch it's not but am not sure if there's a way to check.

**Comment by grantalewis** [comment]
Any thoughts on the above?

**Comment by grantalewis** [comment]
The problem still exists as described above, but I made an  interesting discovery. Although the toggle for the entity still goes "dead," I found out that I can still operate entities through the Services panel:

https://i.imgur.com/SVLPhUq.png

Running HA (Hass.io) 0.90.2 on VirtualBox, Ubuntu 64.

**Comment by thecynic** [comment]
I think this has been fixed. Please advise if not.

**Comment by grantalewis** [comment]
Yes! Resolved. Thanks!
